### ISSUE TITLE
Please share the steps how to run the Betweenness Centrality code in cuda.

### ISSUE THREAD

**Issue by sharanyakamath** [woofilee/GraphHPC-2017#1]
I don't know how to run the main.cu file. Would be really helpful if you put the steps in the readme. Thanks

**Comment by nariman** [comment]
@sharanyakamath 
Probably, the main difficulty in running the solution is an unusual input format. Input data is a binary-encoded file.
Let me some time to reproduce the working state.

**Comment by nariman** [comment]
Unfortunately, I don't have compilation tools on my home laptop to test the solution and write the correct instructions.
I've committed the reference files. You can find the folder [here](https://github.com/narimanizett/graphhpc-2017/tree/master/reference).

There's test generation tool. Just compile it by `make` and then generate some tests by `gen_random` or `gen_RMAT` binaries. The `-s` option is a graph size (exponent, the base is 2).
Then, you can provide the test to the solution (use `-in` option). You must provide the `-nIters` option - the number of solution iterations. Pass `1` if it's unnecessary for you.
You can validate answer as well, validation tool is bundled with the reference files.
The reference's README may clarify things a bit for you, if needed.

I'll write the steps in my README file when I'm back at work tomorrow.

**Comment by sharanyakamath** [comment]
Thanks
